# TP6

### `Resolver usando Pandas`

Resolver los ejercicios del TP3 utilizando la librer√≠a Pandas.

### Ejercicio 1: Cargar Datos de ventas.

El archivo datos.dat contiene el registro de las ventas realizadas.

Tiene un formato de ancho fijo:
- `fecha`:    10 lugares
- `producto`: 30 lugares
- `precio`:   10 lugares
- `cantidad`:  5 lugares

Hacer una funcion que cargue los datos en un DataFrame de Pandas.

In [4]:
import pandas as pd

def cargar_datos():
    colspecs = [(0, 10), (10, 40), (40, 50), (50, 55)]
    column_names = ['fecha', 'producto', 'precio', 'cantidad']
    
    df = pd.read_fwf(
        "datos.dat", 
        colspecs=colspecs, 
        names=column_names
    )
    
    df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d')
    df['precio'] = df['precio'].astype(float)
    df['cantidad'] = df['cantidad'].astype(int)
    
    return df

datos = cargar_datos()

datos

        fecha    producto  precio  cantidad
0  2024-08-27     Mirinda  1510.0        14
1  2024-08-27     Mirinda  1560.0        12
2  2024-08-28     Torasso   940.0         8
3  2024-08-29  Pepsi Cola  1210.0        10
4  2024-08-30     Mirinda  1520.0         1
5  2024-09-01     Mirinda  1550.0        15
6  2024-09-01      Sprite   810.0         4
7  2024-09-02   Coca Cola  1100.0         4
8  2024-09-02  Pepsi Cola  1220.0        13
9  2024-09-02     Torasso   910.0         5
10 2024-09-02     Torasso   920.0         3
11 2024-09-03   Coca Cola  1020.0         8
12 2024-09-03     Mirinda  1570.0         7
13 2024-09-03     Mirinda  1590.0         2
14 2024-09-04  Pepsi Cola  1220.0        13
15 2024-09-05     Mirinda  1500.0         3
16 2024-09-05  Pepsi Cola  1300.0         5
17 2024-09-06   Coca Cola  1080.0         1
18 2024-09-06      Sprite   860.0        12
19 2024-09-06     Torasso   930.0         3
20 2024-09-07   Coca Cola  1080.0        14
21 2024-09-07      Sprite   870.0        13
22 2024-09-08   Coca Cola  1040.0        10
23 2024-09-08     Mirinda  1580.0         2
24 2024-09-08  Pepsi Cola  1240.0         9
25 2024-09-09     Mirinda  1500.0         3
26 2024-09-09      Sprite   850.0         9
27 2024-09-10     Mirinda  1590.0         8
28 2024-09-10  Pepsi Cola  1250.0        12
29 2024-09-11      Sprite   810.0         6
30 2024-09-11      Sprite   820.0        14
31 2024-09-12   Coca Cola  1080.0         4
32 2024-09-13     Mirinda  1580.0         5
33 2024-09-13  Pepsi Cola  1250.0        13
34 2024-09-14   Coca Cola  1080.0        15
35 2024-09-14  Pepsi Cola  1270.0        14
36 2024-09-15   Coca Cola  1100.0         1
37 2024-09-15     Mirinda  1500.0        13
38 2024-09-15      Sprite   870.0        14
39 2024-09-15     Torasso   900.0        13

### Ejercicio 2: Calcular el total de ventas.
Hacer una funci√≥n que sume los importes vendidos (precio * cantidad) y las cantidades.

In [ ]:
def calcular_totales(datos):

    datos['importe'] = datos['precio'] * datos['cantidad']
    importe_total = datos['importe'].sum()
    cantidad_total = datos['cantidad'].sum()
    return importe_total, cantidad_total


importe, cantidad = calcular_totales(datos)

print(f"Las ventas fueron de ${importe:.2f} en {cantidad} unidades")

Las ventas fueron de $392730.00 en 335 unidades

### Ejercicio 3: Listar las unidades vendidas.
Listar cu√°ntas unidades se vendieron en total para cada producto

In [ ]:
def unidades_vendidas(datos):
    resumen = datos.groupby('producto')['cantidad'].sum().reset_index()
    resumen = resumen.rename(columns={'cantidad': 'unidades_vendidas'})
    return resumen


resumen_ventas = unidades_vendidas(datos)

print(resumen_ventas)

     producto  unidades_vendidas
0   Coca Cola                 57
1     Mirinda                 85
2  Pepsi Cola                 89
3      Sprite                 72
4     Torasso                 32

###  Ejercicio 4: Listar el precio promedio por producto.
Hacer un listado del precio promedio por producto.

In [9]:
def precio_promedio(datos):
    promedio = datos.groupby('producto')['precio'].mean().reset_index()
    promedio = promedio.rename(columns={'precio': 'precio_promedio'})
    return promedio

resultado = precio_promedio(datos)
print(resultado)

     producto  precio_promedio
0   Coca Cola      1072.500000
1     Mirinda      1545.833333
2  Pepsi Cola      1245.000000
3      Sprite       841.428571
4     Torasso       920.000000

### Ejercicio 5: Ranking de productos
Realizar un listado de los 3 productos m√°s vendidos ordenados por la cantidad de unidades vendidas (ordenadas de mayor a menor)

In [12]:
def ranking_productos(datos, top=3):
    ranking = datos.groupby('producto')['cantidad'].sum().reset_index()
    ranking = ranking.rename(columns={'cantidad': 'unidades_vendidas'})
    
    ranking = ranking.sort_values(by='unidades_vendidas', ascending=False).head(top)
    return ranking

resultado_ranking = ranking_productos(datos)
print(resultado_ranking)

     producto  unidades_vendidas
2  Pepsi Cola                 89
1     Mirinda                 85
3      Sprite                 72

### Ejercicio 6: Listar las ventas por mes
Realizar un listado del total de unidades vendidas por producto separado por mes.

In [13]:
def ventas_por_mes(datos):
    datos['mes'] = datos['fecha'].dt.to_period('M')
    
    ventas_mensuales = datos.groupby(['producto', 'mes'])['cantidad'].sum().reset_index()
    ventas_mensuales = ventas_mensuales.rename(columns={'cantidad': 'unidades_vendidas'})
    
    return ventas_mensuales

resultado_ventas_por_mes = ventas_por_mes(datos)
print(resultado_ventas_por_mes)

     producto      mes  unidades_vendidas
0   Coca Cola  2024-09                 57
1     Mirinda  2024-08                 27
2     Mirinda  2024-09                 58
3  Pepsi Cola  2024-08                 10
4  Pepsi Cola  2024-09                 79
5      Sprite  2024-09                 72
6     Torasso  2024-08                  8
7     Torasso  2024-09                 24

### Ejercicio 7: Informe general

Mostrar un listado de productos ordenados alfabeticamente que contengan el precio promedio, la cantidad de unidades vendidas y el importe total vendido para cada producto

In [14]:
def resumen_ventas(datos):
    # Calcular el precio promedio, cantidad de unidades vendidas e importe total por producto
    resumen = datos.groupby('producto').agg({
        'precio': 'mean',
        'cantidad': 'sum',
        'importe': 'sum'
    }).reset_index()

    resumen = resumen.rename(columns={
        'precio': 'precio_promedio',
        'cantidad': 'unidades_vendidas',
        'importe': 'importe_total'
    })

    resumen = resumen.sort_values(by='producto')
    
    return resumen

resultado_resumen = resumen_ventas(datos)
print(resultado_resumen)

     producto  precio_promedio  unidades_vendidas  importe_total
0   Coca Cola      1072.500000                 57        60780.0
1     Mirinda      1545.833333                 85       131080.0
2  Pepsi Cola      1245.000000                 89       110510.0
3      Sprite       841.428571                 72        61040.0
4     Torasso       920.000000                 32        29320.0

## `Resolver usando NumPy`
## Resolver el ejercicio 2 del tp1 usando NumPy

### Ejercicio 8

Escribe una funci√≥n en Python que encuentre los valores de `a`, `b`, y `c` para que la funci√≥n cuadr√°tica `f(x) = a x^2 + b x + c` pase exactamente por los siguientes puntos:

| x  | y  |
|---:|---:|
|  0 |  0 |
|  1 |  8 |
|  2 | 12 |
|  3 | 12 |
|  5 |  0 |

### Requisitos:
- La funci√≥n debe explorar posibles valores de `a`, `b`, y `c` utilizando un m√©todo de prueba y error.
- Debe devolver los valores que hagan que la diferencia entre la funci√≥n `f(x)` y los valores medidos `y` sea exactamente cero para cada punto.

> **Pista**: Los valores de `a`, `b`, y `c` son n√∫meros peque√±os.

La idea es implementar el mismo algoritmo que se uso en el TP1 pero usando NumPy en lugar de Python puro.

In [24]:
import numpy as np

def f(x, coeficientes):
    a, b, c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return y - y_pred

X = np.array([0, 1, 2, 3, 5])
Y = np.array([0, 8, 12, 12, 0])

def buscar_coeficientes():
    A = np.vstack([X**2, X, np.ones_like(X)]).T
    
    coeficientes, _, _, _ = np.linalg.lstsq(A, Y, rcond=None)
    
    coeficientes_enteros = np.round(coeficientes).astype(int)
    return coeficientes_enteros

coeficientes = buscar_coeficientes()
print(coeficientes)

[-2 10  0]

### Ejercicio 9: Resolver el ejercicio 3 del TP1 usando NumPy
Buscar los coeficientes de la funci√≥n que minimice la suma de los cuadrados de las diferencias entre los valores medidos y los valores de la funci√≥n.

1. Crear un array con los coeficientes elegidos al azar (usar `randint(-10,10,3)`).
2. Calcular el valor de la funci√≥n y el error correspondiente.
3. Mientras que el error sea mayor a 1:
    1. Definir nuevos coeficientes agreg√°ndoles un peque√±o valor al azar a los coeficientes actuales (aprendizaje = 0.001).
    2. Si el error para los nuevos coeficientes es menor que el anterior, reemplazar los coeficientes actuales por los nuevos.

In [6]:
import numpy as np
from numpy.random import randint

def f(x, coeficientes):
    a, b, c = coeficientes
    return a * x**2 + b * x + c

def error(y, y_pred):
    return np.sum((y - y_pred)**2)

def buscar_coeficientes():
    coeficientes = randint(-10, 10, 3)

    y_pred = f(X, coeficientes)
    e = error(Y, y_pred)

    while e > 1:
        nuevos_coeficientes = coeficientes + randint(-1, 2, 3) * 0.001

        y_pred_nuevo = f(X, nuevos_coeficientes)
        e_nuevo = error(Y, y_pred_nuevo)

        if e_nuevo < e:
            coeficientes = nuevos_coeficientes
            e = e_nuevo

    return coeficientes

X = np.array([0, 1, 2, 3, 5])
Y = np.array([0, 8, 12, 11, 1])

coeficientes = buscar_coeficientes()
print(coeficientes)

[-1.78   8.959  0.623]